# Name of the item
string item_name

# RMP
temoto_core/RMPRequest trr

---

# Topic where the information about the required
# item is going to be published
string item_topic

# RMP
temoto_core/RMPResponse trr
